### ISSUE TITLE
Need Assistance

### ISSUE THREAD

**Issue by luvher** [mateussouzaweb/kvm-qemu-virtualization-guide#1]
Hi, i'm about to install macOS. But failed hanging at the TianoCore Bootscreen, that might be a problem of a messed up XML editing see Post #3

Here are some specs of my system:
Huananzhi X99-F8D
2x Xeon 2620V3
64 GB DDR4
GPRO 4300

Normally i run the system with an Samsung NVME. For testing purposes i use an old SSD.

**Comment by mateussouzaweb** [comment]
My guide is clearly intended for advanced users, if you don't have knowledge on KVM, you should not follow this guide. Beside this, order than saying how bad my guide is, you don't give any clear description of what is your issue or how we can improve the instructions to solve it.

**Comment by luvher** [comment]
Well, i'm sorry if my words hurt you. On the first page of your guide you say that you can expect an "easy guide" that's little bit confussing. I really apreciate your work. I'm not very into Fedora but i'm addicted to technics and other Linux Distributions and even KVM, not a pro though but also not a newbie.

After i reinstalled everything i'm getting to the Bootscreen of "TianoCore" but that's it. Maybe you can have a look at my *.xml. Btw. I'm trying to install MacOS BigSur.
[macos.txt](https://github.com/mateussouzaweb/kvm-qemu-virtualization-guide/files/8247303/macos.txt)

**Comment by mateussouzaweb** [comment]
@luvher does not hurt, I am just expecting a more constructive issue to help fix problems instead of emptiness discussions.

Ok, MacOS is trick to get working. Have you tried run any Linux distro first? I am saying this because that is a good measure to understand if the issue is the MacOS VM type or it's a global problem...

Could notice from your XML:

- Your hooks are incompatible with the current XML configs. For now, I suggest you using only the ``--scale-cpu`` hook.
- Your install ISO is a bit strange since the ``fetch-macOS-v2.py`` generates an ``.img`` file. Are you sure that this is the correct disk? 
- I recommend using the ``<cpu>`` entry as host-passthrough and let the ``<qemu:command>`` entry fix the CPU.
- Switch the ``<video>`` entry to the sample below. Not totally sure because I can't remember, but I believe that this specific video type is required for MacOS. 

```xml
<video>
  <model type='vga' vram='131072' heads='1' primary='yes'/>
</video>
```

**Comment by luvher** [comment]
I haven't tried Linux first but I was able to install macOS yesterday with the following XML. Install ISO is correct I have the full installation Image for BigSur :-) As I could see everything's work as it should, except the Graphic Acceleration. I only got 1MB Memory and stuck at the Resoultion of 800x600. I know this is because I'm using an unsupported Graphics Card. The GPRO 4300 is almost identical as the WX4100.

If I install macOS directly to this Machine (not as VM) the Graphic Card works perfectly (Metal supported) after injecting the Device-ID from the WX4100 (67E3) in OpenCore under Device Properties including the entry "no-spoof-gfx" for WEG.

I've tried the same method with the GPU Passthrough for VM but failed. I know that the Entry was recognized by macOS as I can change the Name of the Graphics Card in whatever I want to be displayed. So i think there must be a problem in the way the Graphics Card get passthroughed to macOS?

Any help would be very appreciated. If you need further informations let me know.
[macos.txt](https://github.com/mateussouzaweb/kvm-qemu-virtualization-guide/files/8251492/macos.txt)

**Comment by mateussouzaweb** [comment]
@luvher if you already installed it directly, then I believe that you had built the Open Core EFI for your machine, correct? Did you check if there are any special graphics drivers or settings in your EFI that are not available at https://github.com/kholia/OSX-KVM/tree/master/OpenCore? Maybe you need to build the EFI with something like https://dortania.github.io/Getting-Started-With-ACPI/Universal/spoof.html

If you are seeing something on the GPU, then I believe that the issue should be inside the VM only. I have a 5500 XT, only worked after I add the ``agdpmod=pikera`` boot arg...

**Comment by moonsuyoung** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
3for, @JixinZhang, @forestrf, @pawel-piskorz, @crbast, @rurudo-AI, @flavidetosnow, @jasonye1986, @NiekKeijzer, @coderHsc, @Heliumt, @endframe-inc, @chenheard, @SubaruSama, @jerryleooo, @SergeBouchut, @NeoChow, @WesleyJBrown, @MauriceZ, @indidatajones, @thisdk, @17mon, @zhengxiawu, @zhangdavids, @dzlzh, @stonegao, @MEIYINGFLIPPY, @mehmetaydogduu, @zjgooddream, @fedefloris, @axelgon, @trepwq, @Flushot, @slr, @axjs, @bandwagonhost, @foverzar, @songtianyi, @Pigpog, @qqj147258, @gmist, @bradvo, @lennaht, @zereraz, @cocasse, @cmtzco, @anhdowastaken, @rxwen, @iduartgomez, @Zhengbledoredestshadow, @ooooevan, @treedom, @Ag2S1, @breathzi, @mtfcd, @nathanp, @piscolomo, @amalrkc, @esp10mm, @Fruetel, @rhwong, @SuperiorBo, @loyalyonggang, @Daiver, @lyming531, @aferreira44, @askz, @sbmsr, @Antonhansel, @bmolinh, @Angle-bo, @jbgf, @liujiyuan, @gczh, @rt1314, @NDuma, @StSmile, @NanamiSirone, @roohat, @FRiceSchoolAcct, @xiong-kun, @davidomoyele, @sycue, @guizhenwei, @qci133, @andyway, @bbriggs, @stefaneyr, @lbn, @jbloemendal, @mapx, @CodeTalks, @samstarnes, @joke2k, @Awk34, @samyk, @huynhdev24, @zenepc, @Gronghon
