### ISSUE TITLE
Question about IOMMU 

### ISSUE THREAD

**Issue by carraot** [mateussouzaweb/kvm-qemu-virtualization-guide#2]
Hello, I have an Asrock X570 Phantom Gaming 4 motherboard, a ryzen 5 3600 CPU and a Radeon 5500XT. My question is that do i also have to enable AER cap and ACS in the BIOS or just enabling IOMMU is enough to proceed with the guide.

**Comment by mateussouzaweb** [comment]
@carraot Sorry, I just saw your question now. Hope you have already solved that.

For anyone else, I found out this guide (https://www.reddit.com/r/VFIO/comments/cm6xme/comment/ew0r5x7/?utm_source=share&utm_medium=web2x&context=3) and I think is pretty close to any X570. I don't have one here, so cannot confirm, but as rule of thumb, you need to perform some tests to see if something relevant changes by tweaking the motherboard settings...
