### ISSUE TITLE
XML Question

### ISSUE THREAD

**Issue by carraot** [mateussouzaweb/kvm-qemu-virtualization-guide#4]
Hello while I was studying the ubuntu.xml sample I came across these lines

```

    <hostdev mode='subsystem' type='pci' managed='yes'> 
       <source> 
         <address domain='0x0000' bus='0x02' slot='0x00' function='0x0'/> 
       </source> 
       <address type='pci' domain='0x0000' bus='0x0a' slot='0x00' function='0x0'/>

```

Could you please tell me what is this device on the host machine?

**Comment by mateussouzaweb** [comment]
@carraot every ``<hostdev>`` entry is related to my hypervisor hardware and it will not match your hardware. In my case, that is the USB controller. I do recommend you to remove this entry and assign a new one if necessary.

**Comment by carraot** [comment]
> @carraot every ``<hostdev>`` entry is related to my hypervisor hardware and it will not match your hardware. In my case, that is the USB controller. I do recommend you to remove this entry and assign a new one if necessary.

alright thanks
